### ISSUE TITLE
CALLER_PKG not introspected from flows

### ISSUE THREAD

**Issue by jaklinger** [nestauk/daps_utils#46]
`db_session` and `get_mysql_engine` will fail with:

```AttributeError: 'NoneType' object has no attribute 'config'```

The actual code for this is in `parse_caller.py` --> `get_main_caller_pkg`:

```python
    if '/flows/' in _caller and _caller.startswith('/tmp/'):
        return None
    # Exception for metaflow flows run from AWS batch                                      
    if _caller.startswith('/metaflow/'):
        return None
```

in the meantime, one workaround is putting:

```python
import ojd_daps
from daps_utils import db
db.CALLER_PKG = ojd_daps  # <-- monkey patch the calling package in
db_session = db.db_session
```

at the top of your flow file

**Comment by bishax** [comment]
Again, the concept of caller package is a code smell. 
Perhaps `daps_utils` should be a git submodule within a DAPS?

It can still be installed / updated as desired and but it would be closer to being a first-class component of a DAPS

**Comment by jaklinger** [comment]
It's not nice - and in a general submodule would be less smelly... but metaflow wouldn't be able to access the submodule (because it's upstream).

But agreed, this is just a submodule workaround... and at least the smell is confined to one place, with the door closed

**Comment by bishax** [comment]
Ugh, bloody metaflow.
Though it would be able to access the submodule with the flow utils (on batch / separated env) or as-is running locally.
