### ISSUE TITLE
object_as_dict doesn't work with ORM-instrumented descriptor queries

### ISSUE THREAD

**Issue by jooh** [nestauk/daps_utils#77]
[`object_as_dict`](https://github.com/nestauk/daps_utils/blob/dab9fa3a1b7a621a6e7559632982004f5444f3fa/daps_utils/db.py#L16-L19) is handy for taking a record from a query and converting it to a python dict. But it can only do this on queries formed by passing the Base ORM, e.g. `session.query(RawJobAd)`. If you instead query specific columns with `session.query(RawJobAd.id, RawJobAd.description)`, you get a non-Inspectable return instance that causes an exception.

I added a version that can handle both cases to my ojd_daps branch [here](https://github.com/nestauk/ojd_daps/blob/4b909011edd8444c233d63dfca6f44d79ca9eb17/ojd_daps/flows/enrich/labs/requires_degree/model/io.py#L49-L62).

If this looks promising I can do a little PR to bring it back to daps_utils.

**Comment by jaklinger** [comment]
Looks great, thanks for this
