### ISSUE TITLE
Action to resolve `VERSION` merge conflicts on all active PRs

### ISSUE THREAD

**Issue by jaklinger** [nestauk/daps_utils#79]
After every merge to `dev` all other active PRs end up with a conflicted `VERSION` (between the feature head and `dev`). To resolve this we can implement an action which:

* Is deployed on merge to `dev`
* Uses the GitHub API to iterate through all *open* PRs which are merging to `dev`
* Checkout the branch of that PR using the python `sh` package to wrap up `git`
* Do `git pull && git merge dev` (or the python `sh` equivalent)
* "Manually" resolve conflicts in `VERSION`, picking the head over `dev`, then commit the change and push
* Repeat for all *open* PRs which are merging to `dev`

**Comment by bishax** [comment]
I'd argue that solving a simple merge conflict is less hassle than the following situation:
- I'm working on my feature branch
- Someone merges a PR into dev which triggers the GH action to commit to my feature branch
- I go to push my changes (without pulling first because no-one else is working on this branch)
- My push is rejected

**Comment by jaklinger** [comment]
@jooh see Alex's comment (we were discussing this)

Yeah, those are fair points @bishax, in which case a git hook (post commit?) would actually be a better option since it would keep the committer in the loop, and "manually" triggering it would simply be a case of triggering an empty commit.

**Comment by jooh** [comment]
On further research it it seems a better way to handle this is with a merge driver, which basically would ensure that conflicts for this specific file are always resolved with `--ours`.

Is there any scenario in which you *don't* want to resolve merges in this way automatically? Would you ever need to commit to the repo without changing `VERSION`?

**Comment by jaklinger** [comment]
If anything, we would want to take that option out of the developers hands all together so the merge driver sounds like the perfect solution, and very very lightweight

**Comment by jaklinger** [comment]
(and for that specific file it should only ever be `ours` since the intention of the version is to match the code version to feature branch in question)

**Comment by jooh** [comment]
I have a prototype for this now. It should be implemented as a PR on `ojd_daps` right?

**Comment by jaklinger** [comment]
Both here and there actually, thanks!
